CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Roles" (
    "RoleId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Type" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
);

CREATE TABLE "Users" (
    "UserId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "Status" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "RoleId" bigint NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE CASCADE
);

CREATE TABLE "Client" (
    "ClientId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(50) NOT NULL,
    "LastName" varchar(50) NOT NULL,
    "Age" smallint NOT NULL,
    "Genre" varchar(1) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_Client" PRIMARY KEY ("ClientId"),
    CONSTRAINT "FK_Client_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Client_UserId" ON "Client" ("UserId");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230329070423_FirtsMigrations', '7.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ALTER COLUMN "RoleId" SET DEFAULT 1;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230330070302_SecondMigration', '7.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ALTER COLUMN "Status" DROP NOT NULL;

ALTER TABLE "Users" ADD CONSTRAINT "AK_Users_Email" UNIQUE ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230405054015_ThirdMigration', '7.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Client" DROP CONSTRAINT "FK_Client_Users_UserId";

ALTER TABLE "Client" DROP CONSTRAINT "PK_Client";

DROP INDEX "IX_Client_UserId";

ALTER TABLE "Client" RENAME TO "Clients";

ALTER TABLE "Clients" ADD "Status" boolean NULL DEFAULT TRUE;

ALTER TABLE "Clients" ADD CONSTRAINT "AK_Clients_UserId" UNIQUE ("UserId");

ALTER TABLE "Clients" ADD CONSTRAINT "PK_Clients" PRIMARY KEY ("ClientId");

ALTER TABLE "Clients" ADD CONSTRAINT "FK_Clients_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230406025246_FourthMigration', '7.0.4');

COMMIT;

START TRANSACTION;

CREATE TABLE "AccountType" (
    "AccountTypeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100) NOT NULL,
    "RegDate" timestamp with time zone NULL DEFAULT (now()),
    CONSTRAINT "PK_AccountType" PRIMARY KEY ("AccountTypeId")
);

CREATE TABLE "Account" (
    "AccountId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Balance" money NOT NULL DEFAULT 0.0::money,
    "CreatedAt" timestamp with time zone NULL DEFAULT (now()),
    "ClientId" bigint NOT NULL,
    "AccountTypeId" bigint NOT NULL,
    CONSTRAINT "PK_Account" PRIMARY KEY ("AccountId"),
    CONSTRAINT "FK_Account_AccountType_AccountTypeId" FOREIGN KEY ("AccountTypeId") REFERENCES "AccountType" ("AccountTypeId") ON DELETE CASCADE,
    CONSTRAINT "FK_Account_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE
);

CREATE INDEX "IX_Account_AccountTypeId" ON "Account" ("AccountTypeId");

CREATE INDEX "IX_Account_ClientId" ON "Account" ("ClientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230411042854_FifthMigration', '7.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Account" DROP CONSTRAINT "FK_Account_AccountType_AccountTypeId";

ALTER TABLE "Account" DROP CONSTRAINT "FK_Account_Clients_ClientId";

DROP TABLE "AccountType";

ALTER TABLE "Account" DROP CONSTRAINT "PK_Account";

ALTER TABLE "Account" RENAME TO "Accounts";

ALTER INDEX "IX_Account_ClientId" RENAME TO "IX_Accounts_ClientId";

ALTER INDEX "IX_Account_AccountTypeId" RENAME TO "IX_Accounts_AccountTypeId";

ALTER TABLE "Accounts" ADD CONSTRAINT "PK_Accounts" PRIMARY KEY ("AccountId");

CREATE TABLE "AccountTypes" (
    "AccountTypeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100) NOT NULL,
    "RegDate" timestamp with time zone NULL DEFAULT (now()),
    CONSTRAINT "PK_AccountTypes" PRIMARY KEY ("AccountTypeId")
);

ALTER TABLE "Accounts" ADD CONSTRAINT "FK_Accounts_AccountTypes_AccountTypeId" FOREIGN KEY ("AccountTypeId") REFERENCES "AccountTypes" ("AccountTypeId") ON DELETE CASCADE;

ALTER TABLE "Accounts" ADD CONSTRAINT "FK_Accounts_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230411062051_SixthMigration', '7.0.4');

COMMIT;