version: '3.1'

services:
  db:
    image: postgres
    container_name: bankApi
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "./postgres:/var/lib/postgresql/data"